### ISSUE TITLE
RNA mode

### ISSUE THREAD

**Issue by km-2021** [ChristofferFlensburg/superFreq#107]
Hi,

"'RNA' has some minor changes when running on RNA.", what specific changes are needed?

**Comment by ChristofferFlensburg** [comment]
RNA as in `mode="RNA"` just has a few small differences in the algorithm for variant calling and copy number calling, due to differences from exomes and genomes, in particular to handle a more variable read depth in RNA-Seq. No changes are needed on your end, just set mode to RNA if you're analysing RNA-Seq data.
