### ISSUE TITLE
Questions regarding the MAFstat plots

### ISSUE THREAD

**Issue by gilhornung** [ChristofferFlensburg/superFreq#11]
Hi Christoffer,

Couple of questions regarding the MAFstat plots:

1) Why do I see two figures in the pdf for each sample? Which one is informative?
![mafstat](https://user-images.githubusercontent.com/25452585/28120355-79cfab2c-6720-11e7-8092-d4814c850d66.PNG)

2) Why are my normal samples not in the range of the "null" hypothesis?
![maf_normal](https://user-images.githubusercontent.com/25452585/28120421-b0128a88-6720-11e7-84b6-73575d3abc8c.PNG)

**Comment by ChristofferFlensburg** [comment]
1. The first page is zoomed in on the y-axis, which is good to spot noisy null regions from low clonality true signals. The second zoomes out to largest value, and (hopefully) confirms that the strong CNA regions are on point.

2. Usually because the heterozygous SNP VAFs have a wider variance than superFreq estimates. They still don't match the alternative frequency very well, and they are barely below the line, so I guess few (or none) of those get called as CNAs based on the SNPs? You can increase variance estimate of the SNP VAFs by decreasing maxCov a bit, which may help with your ploidy estimates as well. Maybe start with trying 100 instead of default 150.

**Comment by gilhornung** [comment]
Thanks for the clarification!
Gil
