### ISSUE TITLE
Plot interpretation

### ISSUE THREAD

**Issue by Teezi** [ChristofferFlensburg/superFreq#126]
Hi Chris,

Are there any resources available for users to learn about and interpret the plots? Many thanks!

**Comment by ChristofferFlensburg** [comment]
The manual here on github is 5 years old, but has a fair bit of content on how to read the plots. I've added a few things since, but the manual should be a good start. If you want something specific that you cant find in the manual, then it might be worth having a search here in the issues, I think I've answered a few questions like that.

**Comment by Teezi** [comment]
> The manual here on github is 5 years old, but has a fair bit of content on how to read the plots. I've added a few things since, but the manual should be a good start. If you want something specific that you cant find in the manual, then it might be worth having a search here in the issues, I think I've answered a few questions like that.

Thanks!
