### ISSUE TITLE
Having issues downloading

### ISSUE THREAD

**Issue by jdchang1** [ChristofferFlensburg/superFreq#17]
Hi,

I am unfortunately having some problems installing superFreq to my systems. Here is the issue that I am having.

![image](https://user-images.githubusercontent.com/19615071/29323699-ac41228a-81af-11e7-8c40-aeabee139712.png)
 Thank you!

**Comment by ChristofferFlensburg** [comment]
Hi Jonathan,

I ran into the exact same problem with collaborator just yesterday. I added a fix, adding the line "biocViews:" to the DESCRIPTION 23h ago as of writing, which solved the problem for us. Your issue is only 8h old, but I am not sure if you got this error before or after my fix. Maybe I broke it for you by adding that line.

So first try installing again, just to make sure that it is with the fix. If that fails, try on the earlier commit by:
install_github('ChristofferFlensburg/superFreq', ref='1d934e7aa4acaaaa0029243711c2794341a55416')

If both of those fail, I will have to look into it closer.

Good luck and all the best,
/Christoffer

**Comment by jdchang1** [comment]
Hi Christoffer,

Thank you so much for the fast response. I have just tried to install it again, but I am still running into some problems. The installation did progress much further than it did last time; however, half a minute into the installation I got the following message:
![image](https://user-images.githubusercontent.com/19615071/29342300-f8636932-81f7-11e7-84d6-80c0325a58d4.png)

Also, I did try the older installation that you have provided and that too did not work.

Thank you so much again.

Best,
Jonathan

**Comment by ChristofferFlensburg** [comment]
Seems like it decided that it didn't want to install GenomeInfoDb. For now, can you try installing it manually with

```
source("https://bioconductor.org/biocLite.R")
biocLite("GenomeInfoDb")
```

If that doesn't work, maybe you can give me the full output of the installation, together with your sessionInfo()?

Thanks,
/Christoffer

**Comment by ChristofferFlensburg** [comment]
Also I just pushed 0.9.19 online, so you probably want to reinstall again. It should be a bit faster.

**Comment by jdchang1** [comment]
Thank you Christoffer! I have successfully been able to install superFreq. I hope you have a wonderful rest of the week!

Best,
Jonathan
