### ISSUE TITLE
Too low estimate for VAF in the "normal" samples

### ISSUE THREAD

**Issue by gilhornung** [ChristofferFlensburg/superFreq#26]
Hi Chrisoffer,

Issue which was mentioned in [#18](https://github.com/ChristofferFlensburg/superFreq/issues/18):
I see many CNV segments with low VAF, and are called as copy-neutral loss, in the normal sample!

I looked at one of the tumor normal samples scatter plots (see below) and it does some a bit messy.

Furthermore, I tried to trace one of these copy-neutral loss regions. I used x between 206646491 and  209849698. superFreq reports there 77 snps in this region, which I understand as 77 snps that support the low VAF:
```
> as_data_frame(clusters$WS10.N$clusters) %>% filter(call=="AA", Nsnps>50)
# A tibble: 5 × 26
          x1         x2          M      width       df   var   cov Nsnps
       <dbl>      <dbl>      <dbl>      <dbl>    <dbl> <dbl> <dbl> <int>
1  206646491  209849698 0.08931449 0.02489065 5.729432   516  2555    77
2 1021340855 1022182666 0.09980147 0.02433992 5.729432   238  1492    54
3 1094798263 1095153061 0.09456790 0.05402365 5.729432   695  4006   125
4 1680467974 1683588243 0.15199877 0.03490651 5.729432   492  2498    74
5 2549880663 2557646472 0.05724452 0.02060535 5.729432   506  2122    67
# ... with 18 more variables: pHet <dbl>, pAlt <dbl>, odsHet <dbl>, f <dbl>,
#   stat <dbl>, nullStat <dbl>, altStat <dbl>, nullStatErr <dbl>,
#   altStatErr <dbl>, postHet <dbl>, ferr <dbl>, call <chr>, clonality <dbl>,
#   clonalityError <dbl>, sigma <dbl>, pCall <dbl>, subclonality <dbl>,
#   subclonalityError <dbl>
```

But I was not able to get 77 snps when I looked at the variants in this region:
```
> as_data_frame(allVariants$variants$variants$WS10.N) %>% filter(x>=206646491 & x<=209849698)
# A tibble: 286 × 34
           x reference variant   cov   ref   var       pbq   pmq       psr
       <dbl>     <chr>   <chr> <dbl> <dbl> <dbl>     <dbl> <dbl>     <dbl>
1  206647742         A       G    29     0    29 1.0000000     1 1.0000000
2  206647787         T       A     2     2     0 0.4354090     1 0.4129555
3  206647787         T       C    39     2    37 0.4354090     1 0.4129555
4  206648378         G       A     4     0     4 1.0000000     1 1.0000000
5  206650852         C      +A     2     0     2 1.0000000     1 1.0000000
6  206664396         A       T    27     0    27 1.0000000     1 1.0000000
7  206664407         T       G    33     3    30 0.4457963     1 1.0000000
8  206665896         C       G    37     2    35 0.5472219     1 1.0000000
9  206667441         G       A    32     2    30 0.6032855     1 0.1834677
10 206669958         G       A    26     4    22 0.3458932     1 0.2183946
# ... with 276 more rows, and 25 more variables: RIB <dbl>, flag <chr>,
#   db <lgl>, dbMAF <dbl>, dbValidated <lgl>, exac <lgl>, exacAF <dbl>,
#   exacQual <dbl>, exacFilter <chr>, inGene <chr>, somaticP <dbl>,
#   germline <lgl>, type <chr>, severity <dbl>, polyPhen <chr>, sift <chr>,
#   exon <chr>, AApos <chr>, AAbefore <chr>, AAafter <chr>, domain <chr>,
#   cosmic <chr>, isCosmicCensus <lgl>, cosmicVariantMPM <dbl>,
#   cosmicGeneMPMPB <dbl>

> as_data_frame(allVariants$variants$variants$WS10.N) %>% filter(x>=206646491 & x<=209849698) %>% filter(somaticP>0)
# A tibble: 6 × 34
          x reference variant   cov   ref   var       pbq         pmq       psr
      <dbl>     <chr>   <chr> <dbl> <dbl> <dbl>     <dbl>       <dbl>     <dbl>
1 206761269         G       A    50    30    20 0.3858468 1.000000000 0.2789268
2 207102324         A       G    10     6     4 0.3987114 1.000000000 1.0000000
3 207241440         A +GTGTGT     6     2     4 0.7798546 0.723673610 0.3333333
4 207273399         A      -4    16    14     2 0.3786304 0.004809172 1.0000000
5 207520610         A      +T    19    16     3 0.3651381 0.001151524 1.0000000
6 207679348         G       A    54    31    23 0.7474056 0.446347339 0.3701066
# ... with 25 more variables: RIB <dbl>, flag <chr>, db <lgl>, dbMAF <dbl>,
#   dbValidated <lgl>, exac <lgl>, exacAF <dbl>, exacQual <dbl>,
#   exacFilter <chr>, inGene <chr>, somaticP <dbl>, germline <lgl>, type <chr>,
#   severity <dbl>, polyPhen <chr>, sift <chr>, exon <chr>, AApos <chr>,
#   AAbefore <chr>, AAafter <chr>, domain <chr>, cosmic <chr>,
#   isCosmicCensus <lgl>, cosmicVariantMPM <dbl>, cosmicGeneMPMPB <dbl>
```

Can you please help?

Thank you,

Gil
![all](https://user-images.githubusercontent.com/25452585/32415324-d87bf902-c240-11e7-80f2-00aed368461e.png)

**Comment by ChristofferFlensburg** [comment]
Seems like there are 286 SNVs in the region? The somatic variants are not used to call CNAs, we want the germline variants for that. There is a quality filter for $q == '' though, ie no quality issue flags.

Looking at the scatter, seems like there is a fair amount of noise, both at low frequency (~10%) and just below 1 (~90%). I can't tell at this point what the source of this is (or as far as I know I it could be real, but I guess not). First step could be to look at the small CNN LOF calls in the by-chromosome CNA plots, and see if they look real. A real call will have well defined regions of lof VAF, and close to 0.5 otherwise, while false calls will have more of a mix of low and 0.5 everywhere.

**Comment by gilhornung** [comment]
Hi Christoffer,

Here is the chromosome 1 image. it is clear that there are small regions that are labeled as CNN, but are due to noise (I am working on FFPE, so everything is very noisy). How can I filter out these regions (make the clustering less sensitive)?

![chr1](https://user-images.githubusercontent.com/25452585/32442132-fd793a0e-c302-11e7-80bf-c6fd487dd778.png)

**Comment by ChristofferFlensburg** [comment]
Right, FFPE. Yes, that does make it noisy, and superFreq's filters struggle a bit to catch the FFPE induced SNVs, as there is essentially no way to tell a FFPE-induced SNV from a real (low clonality) one. The alignment and base quality usually look ok, and they won't typically be in the reference normals as the changes are mostly random.

Easiest way for you to handle the messy CNAs is to (effectively) switch off the SNP VAF part by setting maxCov to 1 (or 0 maybe also works?). This will make superFreq call CNAs from the coverage only, which is also pretty messy in FFPE as I understand, but maybe a bit less so than the VAFs. That won't remove them from the somatic SNVs though.

Another alternative is to pre-filter the input VCF on low frequency SNVs of the FFPE base transition change (C to T right?), which will remove them from the superFreq analysis, and you will be able to use the other base transitions to call copy numbers. This will remove the somatic mutations with that base transition though, which can lead to unwanted false negatives. Maybe you can find a VAF cut that removes most of the FFPE noise but retains somatic SNVs with high enough VAF that you care about them? Like 20% or so maybe?

**Comment by gilhornung** [comment]
Are you suggesting that I will do it only for the problematic sample (which I know is "Normal" and hence I expect it not to have CNA or somatic mutations)?

I don't see such an effect in the other samples, so maybe I do need to treat this sample differently?

Also I noticed that that for this specific sample I see a lot of variants in the somaticVariants.xls file (~3000) whereas in all other samples I typically see 10s-100 of mutations. This is probably connected. This sample has more variants. However, only ~1000 variants out of the 3000 are with freq<0.2.

**Comment by ChristofferFlensburg** [comment]
The setting is common for the entire run, but you can rerun with just the normal alone if you want. :)

You can also just ignore it, if it doesn't pose a problem for the analysis otherwise. As you know what causes the issue, and if it doesn't interfere with your analysis otherwise, I think it's fair to ignore it.

The cancer samples have a matched normal, so they will select heterozygous SNP close to 50% in the matched normal (which will be very few FFPE SNVs), which is why the problem isn't there for the cancer samples. The normal doesn't have a matched normal though, so then superFreq goes to plan B and picks any common population SNVs between 5% and 95% VAF, which will include a fair amount of FFPE variants it seems. This is intended behaviour, with the cancer assuming that the matched normal doesn't have any CNAs, but then CNA calling is performed on the matched normal without that assumption anyway for QC. Intention is that if you detect significant CNAs in the matched normal, you should switch off the normal flag in the metadata and rerun. I can see how this doesn't really give desired output for a FFPE case though...

The same goes for the somatic variants. With a matched normal present, somatic variants are called against that, so any germline variants will be filtered. When no matched normal present, then the soamtics are called from low population frequency variants, which can sometimes range in the thousands. I think there is a flag "germlineLike" or something, in the somaticVariants spreadsheet that flags these variants from clustering with the germline in the clonal analysis...

Either way, if you get what you need from the cancer samples, it should be safe to ignore the FFPE-induced CNA calls in the normal.

**Comment by gilhornung** [comment]
OK.

If this is just specific to the normal samples than I don't need to worry.

Closing. \

Thanks,

Gil
