### ISSUE TITLE
segfaults or anything related to memory

### ISSUE THREAD

**Issue by ChristofferFlensburg** [ChristofferFlensburg/superFreq#4]
superFreq uses a fair bit of memory, and it scales with number of cpus used. Most of the memory is used by the variants calls (typically between 50k and 300k) and all their annotation in all the samples and reference normals.

To decrease memory usage, try these corrections in order of convenience:

1) switch to `splitRun=T` in superFreq() if you have multiple different individuals in the meta data. This will make superFreq run each individual separately, and not store all the samples from all the individuals in memory at the same time.

2) Check what other things are running on the server. Can you easily run it on a cluster with more memory?

3) Decrease the number of cpus. It'll slow things down a bit, but usually runs overnight unless you got a lot of samples/SNVs.

4) Look into decreasing the in-going preliminary variant calls in the VCF. If you have many hundred thousands entries in the VCF, chances are that you can restrict the cuts in the preliminary variant calling

**Comment by GWheelerEB** [comment]
I'm running into segfault issues during the subreads portion, going over the normal samples. Going through your points here:

1. Only running one individual
2. No other programs using meaningful amounts of server resources
3. Number of CPUs set to 24, but watching the usage, it never gets much above 200% (2 CPUs @ 100%). My system has 7 GBs of RAM per CPU for 96 CPUs, and I have not seen the R resource usage get above 1%, so that should not be the issue either.
4. From the log outputs, it doesn't seem like this part is using the VCF calls yet. If it is, I have approximately 200,000 calls.

The odd thing is, I've been able to successfully run superFreq with very similar parameters, but using hg19. This is with hg38. I am unsure why that would make any difference, but it seems worth mentioning.

The error output is below:

` *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: featureCounts(externalNormalBams, annot.ext = captureAnnotation,     useMetaFeatures = F, allowMultiOverlap = T, isPairedEnd = (mode !=         "genome"), minMQS = 10, nthreads = cpus)
 2: doTryCatch(return(expr), name, parentenv, handler)
 3: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 4: tryCatchList(expr, classes, parentenv, handlers)
 5: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        sm <- strsplit(conditionMessage(e), "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && isTRUE(getOption("show.error.messages"))) {        cat(msg, file = outFile)        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
 6: try(featureCounts(externalNormalBams, annot.ext = captureAnnotation,     useMetaFeatures = F, allowMultiOverlap = T, isPairedEnd = (mode !=         "genome"), minMQS = 10, nthreads = cpus))
 7: runDE(bamFiles, sampleNames, externalNormalCoverageBams, captureRegions,     Rdirectory, plotDirectory, genome = genome, normalCoverageRdirectory,     settings = settings, cpus = cpus, forceRedoFit = forceRedoFit,     forceRedoCount = forceRedoCount, forceRedoNormalCount = forceRedoNormalCount,     mode = mode)
 8: analyse(inputFiles = inputFiles, outputDirectories = outputDirectories,     settings = settings, forceRedo = forceRedo, runtimeSettings = runtimeSettings,     parameters = parameters, byIndividual = T, manualStoryMerge = manualStoryMerge,     correctReferenceBias = correctReferenceBias, vepCall = vepCall,     resourceDirectory = resourceDirectory, mode = mode, filterOffTarget = filterOffTarget,     rareGermline = rareGermline, annotationMethod = annotationMethod)
 9: superFreq(metaDataFile, normalDirectory = normalDirectory, Rdirectory = Rdirectory,     plotDirectory = plotDirectory, reference = reference, genome = genome,     BQoffset = BQoffset, cpus = cpus, forceRedo = forceRedo,     systematicVariance = systematicVariance, maxCov = maxCov,     mode = mode, splitRun = splitRun, resourceDirectory = resourceDirectory)
An irrecoverable exception occurred. R is aborting now ...
/igm/apps/sge/sge-8.1.9_install/default/spool/rpl-igmsge01/job_scripts/1593928: line 1: 81621 Segmentation **fault`**

**Comment by ChristofferFlensburg** [comment]
Hmm, yeah memory really shouldn't be an issue in that part of a pipeline. You're correct that the variants are not yet read in to memory at that point, and the low memory usage you see confirms that.

On the other hand, featureCounts is a bit of a black box to me, and sometimes it's doing strange things for weird reasons. I haven't tested much above 10 cpus, and the error does sound memory related. So my first guess would be that featureCounts isn't used to this many cpus, being designed for RNA-Seq, and screws up the memory management in some way.

I would scale down to 10 cpus. For 200k variants you are getting limited decrease in total runtime going from 10 to 24 as there are single thread bottlenecks. You'll go much faster if you can run two patients with 10 cpus each on that machine, see this thread for details on how you can parallelise runs from the same batch: https://github.com/ChristofferFlensburg/superFreq/issues/38.

If the problem persists at 10 cpus, maybe you can send me the logfile (Rdirectory/[sample]/runtimeTracking.log), and I'll look for clues. hg19 and hg38 uses different bed files to count reads over, so might be a problem with those files, but not sure what that would be. Maybe try redownloading the hg38 bed files?

I've wanted to get rid of featureCounts for some while, because it's a bit strange sometimes. And while featureCounts is very fast on a read-name sorted bam file, we deal with position-sorted bam files, and then it's pretty slow. So if you know of a fast read counter R-package, let me know. :P
