### ISSUE TITLE
error in running runSummaryPostAnalysis, looking for log file in wrong folder.

### ISSUE THREAD

**Issue by methylnick** [ChristofferFlensburg/superFreq#42]
Hi there, trying to run `runSummaryPostAnalysis()` and specifying the current working directory which contains the `runtimeTracking.log` for the superFreq analysis run. however, sadly, it appears to be looking for it in the `R` directory which I don't have permissions for. (running on a cluster).

Error:

Running summary post analysis.
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file '/usr/local/R/3.6.0-mkl/bin/runtimeTracking.log': Permission denied

**Comment by ChristofferFlensburg** [comment]
Hey!
`runSummaryPostAnalysis()` needs the same `metaDataFile`, `Rdirectory` and `plots` argument as the `superFreq()` analysis. If not specified, `runSummaryPostAnalysis()` defaults to metadata file, r and plot directories in the current working directory. I think that's the problem here, that your analysis isn't in the working directory, so you need to specify the arguments of `runSummaryPostAnalysis()`.

Maybe I should remove the defaults from that function for this reason... 🤔 

If that doesn't solve it, maybe you can show the full `superFreq()` and `runSummaryPostAnalysis()` commands you are running, and I can look closer.

**Comment by methylnick** [comment]
Hi Christoffer, 

I have tried multiple ways of explicitly specifying the paths and files. and tried a few paths to the R directory (R executable, and the current analysis directory, which is what I think this argument is after).

It is almost, where it is looking for the `runtimeTracking.log` is hard-coded upon first run. 

I ran:

runSummaryPostAnalysis() and it returned the same error as running this:

runSummaryPostAnalysis(metaDataFile='/scratch/ha75/2019-07-16-ExomeSeq_Run1/SuperFreq/metadataLMM.tsv', Rdirectory='/scratch/ha75/2019-07-16-ExomeSeq_Run1/SuperFreq', plotDirectory='/scratch/ha75/2019-07-16-ExomeSeq_Run1/SuperFreq/plots_LMM', cpus=4, genome='hg38'Running summary post analysis.
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file 'R/runtimeTracking.log': No such file or directory
>

**Comment by ChristofferFlensburg** [comment]
Yeah, that looks strange. Can you give me the `superFreq()` command you used as well, so I can compare them? Thanks!

**Comment by ChristofferFlensburg** [comment]
Wait, I think I found the bug! Should be quick fix, hang on 10 mins. :D

**Comment by ChristofferFlensburg** [comment]
Ok, the fix was indeed less than 10 minutes, but add on an hour for a VPN disconnect mid-commit, corrupted locked files and lots of fun! Either way, 1.3.1 is online now, hopefully should fix this issue. Just have all the arguments match between `superFreq()` and `runSummaryPostAnalysis()`. Sorry about the mess. :P

**Comment by methylnick** [comment]
sorry mate, now it's looking for something else. 

I ran `superFreq()` on the command line with `Rscript <runSuperFreq.R>` so no `.RProj.user` was made.......hmmmmmm

See below:


runSummaryPostAnalysis(metaDataFile='/scratch/ha75/2019-07-16-ExomeSeq_Run1/SuperFreq/metadataLMM.tsv', Rdirectory='/scratch/ha75/2019-07-16-ExomeSeq_Run1/SuperFreq', plotDirectory='/scratch/ha75/2019-07-16-ExomeSeq_Run1/SuperFreq/plots_LMM', cpus=4, genome='hg38')
Running summary post analysis.
Finding frequently mutated genes as Genes of Interest...Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file '/scratch/ha75/2019-07-16-ExomeSeq_Run1/SuperFreq/.Rproj.user/allVariants.Rdata', probable reason 'No such file or directory'

**Comment by ChristofferFlensburg** [comment]
Wait, you set the main project directory as the Rdirectory? Can you show the runSuperFreq.R file? Whatever you have on the `superFreq()` call.

I realise now that it's assumed that the Rdirectory and the plotsDirectory are new directories used only by superFreq (I normally use myProject/R and myProject/plots or something), and it's getting confused by all the other things in the Rdirectory which is set to your project directory I think.

I should fix that to not be confused, but in the meanwhile, maybe you can create a new directory '/scratch/ha75/2019-07-16-ExomeSeq_Run1/SuperFreq/R', and move the directories with the patient .Rdata (should be '/scratch/ha75/2019-07-16-ExomeSeq_Run1/SuperFreq/myPatient') into that? Then you give '/scratch/ha75/2019-07-16-ExomeSeq_Run1/SuperFreq/R' to `runSummaryPostAnalysis()`. Or wait for me to fix it. :)

Sorry about the mess here, the afterburner is still new and buggy as you notice.

**Comment by methylnick** [comment]
Hmmm, there maybe is bug here, it's `Rdirectory` but none was created, it just ran in the current directory. 


`library(superFreq)

#maximum number of threads. Limited speed up above ~5 cpus for exomes and RNA-Seq and ~10-20 for genomes.
#Better to parallelise across individuals for cohorts, see the cohort section in the github README.
cpus=4

#this is the meta data input. See ?superFreq for how to set it up.
metaDataFile = 'metadataLMM.tsv'

#This directory with (links to) the reference normals needs to be created and set up. See ?superFreq
normalDirectory = 'normals'

#The reference fasta and name. Only hg19, hg38 and mm10 available atm.
reference = 'hg38_ref_noAlt.fa'
genome = 'hg38'

#The directory where the log file and saved .Rdata is stored. Will be created.
Rdirectory = '.'
#The directory where all the plots and tables from the analysis go. Will be created.
plotDirectory = 'plots_LMM'

#The mode. Default 'exome' is for exomes, while 'RNA' has some minor changes when running on RNA.
#There is also a "genome" mode for genomes: ~24h for cancer-normal at 10 cpus, 200GB memory.
mode = 'exome'

#this performs the actual analysis. output goes to Rdirectory and plotDirectory.
#runtime is typically less than 6 hours at 4 cpus for a cancer-normal exome, but can vary significantly depending on input.
#For a typical cancer-normal exome, 5-10GB of memory is used per cpus, but again, can vary significantly depending on input.
#later runs typically a bit faster as the setup and part of the analysis on the reference normals can be reused.
data =
  superFreq(metaDataFile, normalDirectory=normalDirectory,
            Rdirectory=Rdirectory, plotDirectory=plotDirectory, reference=reference, genome=genome,
            cpus=cpus, mode=mode)
`

**Comment by methylnick** [comment]
The little hack with moving things to and `R` directory seems to have worked! okay, I now get the workflow. Understand this is really bleeding edge and appreciate your responsiveness, I hope I am not too annoying with these issues. (I am under the assumption it is helping you improve superFreq) Cheers!

**Comment by ChristofferFlensburg** [comment]
Yep, I appreciate the beta testing and feedback, and you've found two bugs for me already, so I'm happy! :)

In this case it's the `Rdirectory = '.'` part that caught the script off guard. Normally I'd set it to `Rdirectory='R_LMM'` or something, that directory would be created and contain only subdirectories for each individual. Then the afterburner would go into the Rdirectory and (lazily) assume that each subdirectory corresponds to a individual. However, here ther Rdirectory already contains other subdirectories (such as the plots directory and the Rstudio directory), and things crash when the afterburner try to treat them as individuals with .Rdata inside them. So that's pretty bad, and I am making it use the metaDataFile to check which indivudals to expect instead of taking that information from the subdirectories. Will go online next version, but needs a bit more time and testing, so I'm happy to hear that the hack worked for now. I'll leave this issue open until the fix is online.
