### ISSUE TITLE
runSummaryPostAnalysis bug, looking for allVariants.Rdata in wrong folder

### ISSUE THREAD

**Issue by methylnick** [ChristofferFlensburg/superFreq#43]
Hit another bug.

Function looking for the `.RData` file in the plots directory, rather than the patient directory.

-----

 `runSummaryPostAnalysis(Rdirectory ="R", plotDirectory = "plots_LMM", metaDataFile = "metadataLMM.tsv", "hg38", cpus=12)`

Running summary post analysis.
Finding frequently mutated genes as Genes of Interest...Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'R/plots_LMM/allVariants.Rdata', probable reason 'No such file or directory'

**Comment by ChristofferFlensburg** [comment]
This seems like a follow-up bug due to the quick fix I did yesterday. Reminder to self: There are no quick fixes!

I'll sort it out and do a bit more thorough testing this time.

**Comment by ChristofferFlensburg** [comment]
Ok, I spent some time making it handle files based on the actual meta data file, rather than trying to guess (poorly it seems) based on what files are present. Should've done that from the start. Still not super tested, but more tested than last time! There's a fair chance it'll work on your samples now, so update to 1.3.2 and try again, fingers crossed!

For some reason git thought that all files changed, while actually only a few did... huh...
