### ISSUE TITLE
batch mode error from makeCloneScatterPlots 

### ISSUE THREAD

**Issue by andrewrech** [ChristofferFlensburg/superFreq#48]
Hi Christoffer.

I've run into an error and I'm hoping you could help me understand. I'm running superFreq with 2 individuals per cluster node, like so:

```r
  superFreq::superFreq(
    metaDataFile           = metadataFile                       ,
    normalDirectory        = "normals"                          ,
    Rdirectory             = "superFreqData"                    ,
    plotDirectory          = "superFreqPlots"                   ,
    reference              = ref                                ,
    genome                 = "hg38"                             ,
    BQoffset               = 33                                 ,
    outputToTerminalAsWell = TRUE                               ,
    splitRun               = TRUE                               ,
    cpus                   = 96                                 ,
    systematicVariance     = 0.03                               ,
    exacPopulation         = "AMR"                              ,
    rareGermline           = TRUE                               ,
    maxCov                 = 150                                ,
    participants           = participants
  )
```

I run into the following reproducible error:

```
<beginning of log removed>

2020-01-29 09:56:33
Tracking clonal evolution in 13..Found 1368 high quality somatic SNVs to track.
SNVs..
Filtered 1002 small, 9 uncertain, 42 indel and 0 present in normal stories.
Keeping 252 SNV stories.
Tracking clonal evolution in CNVs..57 regions..57 events.
Extracting stories, comparing SNP shift directions..3 overlapping stories filtered..Filtered 26 small, 2 uncertain, 8 small region and 3 present in normal stories.
Filtered 0 stories that are potentially based on false SNPs.
Keeping 23 CNV stories.
merge events into clones..got 10 stories...decide subclone structure..removing inconsistent dodgy clones..got 9 consistent stories...Found 11194 somatic SNVs to track. These will be linked to the found clones.
Found 0 rare germline variants to track.
Filtered 84 present in normal stories.
57 regions..57 events.
Extracting stories, comparing SNP shift directions..3 overlapping stories filtered..restricting to 3000 random mutations in dodgy clustering the interest of time.
Cluster mutations by batch. Remaining clusters: 3001..2678..2319..1905..1398..done!
Marking SNV that behave like germline SNPs..saving variants back to file...done!
Saving stories..done!
2020-01-29 10:13:03
Current memory use (Mb): 1937.5, max use (Mb): 1937.5
2020-01-29 10:13:03
2020-01-29 10:13:03
Summary plot already in place, not redoing.
2020-01-29 10:13:03
2020-01-29 10:13:03
2020-01-29 10:13:03
2020-01-29 10:13:03
2020-01-29 10:13:03
Error in stories[[individual]] : subscript out of bounds
Calls: run_suqerfreq -> <Anonymous> -> superFreq -> analyse -> makeCloneScatterPlots
In addition: There were 94 warnings (use warnings() to see them)
5: makeCloneScatterPlots(variants, stories, samplePairs, individuals,
       timePoints, plotDirectory, genome = genome, cpus = cpus,
       forceRedo = forceRedoScatters)
4: analyse(inputFiles = inputFiles, outputDirectories = outputDirectories,
       settings = settings, forceRedo = forceRedo, runtimeSettings = runtimeSettings,
       parameters = parameters, byIndividual = T, manualStoryMerge = manualStoryMerge,
       correctReferenceBias = correctReferenceBias, vepCall = vepCall,
       resourceDirectory = resourceDirectory, mode = mode, filterOffTarget = filterOffTarget,
       rareGermline = rareGermline, annotationMethod = annotationMethod,
       ploidyPriors = ploidyPriors)
3: superFreq(metaDataFile = input$metaDataFile, captureRegions = captureRegions,
       normalDirectory = normalDirectory, Rdirectory = input$Rdirectory,
       plotDirectory = input$plotDirectory, reference = reference,
       genome = genome, BQoffset = BQoffset, cpus = cpus, outputToTerminalAsWell = outputToTerminalAsWell,
       forceRedo = forceRedo, normalCoverageDirectory = normalCoverageDirectory,
       systematicVariance = systematicVariance, maxCov = maxCov,
       cloneDistanceCut = cloneDistanceCut, resourceDirectory = resourceDirectory,
       mode = mode, splitRun = F, correctReferenceBias = correctReferenceBias,
       vepCall = vepCall, filterOffTarget = filterOffTarget, rareGermline = rareGermline,
       exacPopulation = exacPopulation, cosmicSalvageRate = cosmicSalvageRate,
       annotationMethod = annotationMethod, ploidyPriors = ploidyPriors)
2: superFreq::superFreq(metaDataFile = metadataFile, normalDirectory = "normals",
       Rdirectory = "superFreqData", plotDirectory = "superFreqPlots",
       reference = ref, genome = "hg38", BQoffset = 33, outputToTerminalAsWell = TRUE,
       splitRun = TRUE, cpus = 96, systematicVariance = 0.03, exacPopulation = "AMR",
       rareGermline = TRUE, maxCov = 150, participants = participants) at immune.ml.R#3621
1: run_suqerfreq(metadataFile = "Tempus_PDA_metastatic_DNA_superfreq_key.tsv",
       ref = "Homo_sapiens_assembly38.fasta", participants = c("1",
           "2"))
```

Which is from here:

https://github.com/ChristofferFlensburg/superFreq/blob/12179bee6e1678a580318d69c9d10ec77c30ba76/R/analyse.R#L734-L735

and then here:

https://github.com/ChristofferFlensburg/superFreq/blob/12179bee6e1678a580318d69c9d10ec77c30ba76/R/makeScatterPlots.R#L358

_____

Any idea why this may be occurring? I was able to run the pipeline successfully when I  don't specify participants.

Thanks a lot!

Andrew

**Comment by ChristofferFlensburg** [comment]
Hi Andrew!

The error message (`individual` seems to point to a patient that doesn't exist in the clonal tracking) and the fact that it only happens when you set `participants` points to an error relating to the metadata handling. To investigate further, I'd need the metaDataFile, the value of `participants` at call of `superFreq()`, and the rest of the log file (or at least the start, where the meta data is logged). If you don't feel comfortable sharing publicly on github, you can email to flensburg.c at wehi.edu.au.

Overall though, I think it's better to do a separate `superFreq()` for each individual (aka `participants`), which probably will bypass this error. When called with multiple individuals, it just runs one after the other, so especially when running many individuals on a cluster, there no benefit over separate calls for each individual that can be parallelised.

Also, some parts of the pipeline doesn't parallelise well with threads (as it needs to use all the information at the same time, making it difficult to separate into independent threads), and superFreq doesn't scale that well with more cpus. For exomes, you see limited gain above 10 cpus or so, and it'll be nonlinear gain before that. When I submit larger cohorts of exomes, I usually run with 4 or 6 cpus myself, still goes through in a few hours each for most cases. So 96 cpus is almost certainly very inefficient cpu and memory usage.

I realise that the resource usage isn't well documented anywhere... I think I'll add a section to the README.

I hope that helped, let me know how it goes, or if you need more help!

**Comment by andrewrech** [comment]
Hello again Christoffer,

This error ended up being quite simple. I use numeric (e.g. 1, 2, 3...) individual identities.

In the below line, the object `stories` is a list with the individual identities for element names (class character). However, at some point, `individuals`, if which `individual` is a member, is converted to numeric in my case. Thus, the indexing error. Perhaps `individuals` is a matrix at some point upstream?

https://github.com/ChristofferFlensburg/superFreq/blob/12179bee6e1678a580318d69c9d10ec77c30ba76/R/makeScatterPlots.R#L358 

The fix is along the lines of simply:

```r
storyCluster = stories[[as.character(individual)]]$consistentClusters 
```

Thanks

Andrew

**Comment by ChristofferFlensburg** [comment]
Hi Andrew!

Thanks for sticking with this.

I've never tested with numeric patient names in the meta data, so perfectly possibly that it exposes some bug somewhere. It shouldn't be a matrix at any point, just a named character vector, with sample names as names. I think the problem is that reading from the meta data file with `superFreq:::importSampleMetaData` doesn't enforce that it's a character when imported with read table, and it defaults to a numeric vector when only numbers in the column. Ran a test with numeric individuals:

```
> sampleMetaData = importSampleMetaData('metaData_withNumbersForIndividuals.tsv')
Loading sample meta data from file...done.

> 
> sapply(sampleMetaData, class)
        BAM         VCF  INDIVIDUAL        NAME   TIMEPOINT      NORMAL 
"character" "character"   "integer" "character" "character" "character" 
```

That's fixable by enforcing character type in `importSampleMetaData`: https://github.com/ChristofferFlensburg/superFreq/commit/ef1334780c503dacc18a3386f667fd7c6e0e7343

```
> sampleMetaData = importSampleMetaData('metaData_withNumbersForIndividuals.tsv')
Loading sample meta data from file...done.
> sapply(sampleMetaData, class)
        BAM         VCF  INDIVIDUAL        NAME   TIMEPOINT      NORMAL 
"character" "character" "character" "character" "character" "character" 
```

I think that might've been your problem, but you'll have to update superFreq and rerun to confirm. Possibly you'll have to delete the old run (in R and plots directories, or set forceRedo=forceRedoEverything()) if the old data is stored with numeric-looking meta data, but you may be able to get away with just rerunning with the old data present as well.
Let me know how it goes.

**Comment by andrewrech** [comment]
Hi Chris,

This looks great, thanks a lot for your help! I was able to get it working using basically the same approach in my fork.

Thanks

Andrew
