### ISSUE TITLE
Conflicting annotation

### ISSUE THREAD

**Issue by jlac** [ChristofferFlensburg/superFreq#61]
In running SuperFreq on a few immunotherapy tumors, I noticed that a recurring mutation in a gene of particular interest (B2M) that ablates a start codon is actually getting annotated as a synonymous mutation in a gene (PATL2) that appears to be directly adjacent to B2M. I'm a bit surprised to see this, as I assumed VEP was being run to select the most severe mutational consequence per mutation. Do you know if this is actually the case? Do you know of any other explanation for this, or how best to deal with it within SuperFreq? Thank you in advance, and please let me know if there are any specific files or mutation info that I can provide.

Justin

**Comment by ChristofferFlensburg** [comment]
Hi Justin,

Yeah that is an issue with a few overlapping genes. I am no longer running VEP in superFreq, because it was causing dependency issues for a large number of users, and it was very slow to the point where it became a bottleneck for samples with many somatic mutations. I am now running an R package called VariantAnnotation that removes the dependency issue and is way faster. I am using the Ensembl gene annotation, and in the case of overlapping genes, it sometimes picks the lesser known gene. I am aware of the issue, but it's pretty rare that it affects a gene we care about (so you've been a bit unlucky, sorry), and I am not sure how to fix it, so it hasn't made it to the top of my todo list.

In your case, if you are running a small number of samples, maybe easiest is to handle it "manually", and also look for variants in the overlapping gene and insert them into another variant annotator, such VEP or one of the online ones, and you should get a better description. Or look at them in IGV or whatever. If you want a more automated approach, you can use the VCFs output (in plots/myIndividual/somatics/mySample.vcf) and run VEP or an annotator of your choice.

I'm sorry I can't give you a better solution.
Good luck!
/Christoffer
