### ISSUE TITLE
Error, missing 'cosmicCounts.Rdata' for mm10

### ISSUE THREAD

**Issue by MatthewWiens101** [ChristofferFlensburg/superFreq#65]
Hi,

I have encountered the following issue when running superFreq on mm10 genome in 'RNA' mode:

```
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: superFreq ... superFreq -> analyse -> outputData -> load -> readChar
cannot open compressed file 'superFreqResources/COSMIC/cosmicCounts.Rdata', probable reason 'No such file or directory'
```

Which halts execution. Error happening [here](https://rdrr.io/github/ChristofferFlensburg/superFreq/src/R/outputData.R) in the first load.

I believe this is because cosmicCounts.Rdata, which is usually downloaded when using other genomes, is not downloaded when using mm10, as can be seen [here](https://rdrr.io/github/ChristofferFlensburg/superFreq/src/R/downloadSuperFreqResources.R) in downloadSuperFreqCOSMIC. My question is, can I get around this by simply downloading the file from [here](https://gitlab.wehi.edu.au/flensburg.c/superFreq/blob/bef6d3b1be269189c3cefc6e51a0f3585bd5811b/COSMIC/cosmicCounts.Rdata) and placing it my superFreqResources/COSMIC/ folder? Or will this cause downstream issues? Do you know of any other workarounds? My end goal is to obtain the CNAs as a list for comparison with CNA calls on other datasets and other CNA callers, which seems to be what outputData is trying to do. Thanks in advance, and thanks for providing a great library!

Matthew

**Comment by ChristofferFlensburg** [comment]
Hey Matt,

Yeah putting that file from a differrent run should work as workaraound, and shouldn't cause issues.

It's not downloaded for mm10 runs because it shuldn't be used in mm10 runs (contains human gene information). It seems I forgot to check that it's not mouse when I added the COSMIC census genes as CNA annotation, I'll fix this in next superFreq version, thanks!

**Comment by MatthewWiens101** [comment]
Great thanks! It does seem to be working fine now. I might be able to annotate the CNAs with another program. Just to check, in the CNA.tsv files in the data folder, is M the mean of log fold change? And is width the uncertainty?

Matthew

**Comment by ChristofferFlensburg** [comment]
Yes, that's right. I'm using limma-voom to do that analysis, and some of the differential expression lingo carried over into the column names, sorry. :)
There are also a bunch of stats related to the BAF and whether it's consistent with a null hypothesis of balanced alleles, but you can ignore most of those if you want. Hopefully you can figure out from context which the imporant columns are, otherwise let me know.

Good luck!

**Comment by MatthewWiens101** [comment]
Awesome, and no worries, that makes sense according to the manual, just wanted to be sure. Thanks for your help!
