### ISSUE TITLE
Input to pipeline from different variant caller and segmentation

### ISSUE THREAD

**Issue by gilhornung** [ChristofferFlensburg/superFreq#7]
Hi Christoffer,

1) I want to start the superFreq pipeline from variant calling that I performed using Mutect2 (we find that it identified indels pretty well) that was run on tumor-normal pairs as well as haplotypeCaller vcfs (joint variant calling for all samples). Is there a way to do so?

2) Unfortunately I have only a single "Normal" sample from the same batch as the others. Is there a way to use output from CNVkit or FACETES instead of the usuall workflow?

All the best,

Gil Hornung, PhD
Bioinformatics Analyst
The Nancy and Stephen Grand Israel National Center for Personalized Medicine
Weizmann Institute of Science

**Comment by ChristofferFlensburg** [comment]
Hey Gil!

Thanks for your questions! :)

1. Kindof, but not really. You can give superFreq a .vcf with your somatic SNV/indel calls plus germline SNPs, but there is no way to bypass the superFreq filtering at this point. So as it is now, if superFreq doesn't think that a variant is high enough quality, it'll get flagged and removed from analysis.

2. No, not as it is now, sorry. :/ It runs with any reference normal samples, as long as it is with the same capture regions and same aligner. So while same batch is best, normal samples from other batches from the same lab is usually as good (just hope the PCR settings were not changed in between!). Otherwise anything from same sequencing facilities usually works.

In principle the algorithm is pretty modular and it's in theory perfectly possible to replace the SNV or CNA calling with other methods. In practice however it would probably be some work to parse the input from other SNV/CNA callers into a format that superFreq likes. It's something I wanted to do, and it's been on the todo-list for long, but never very high on the todo-list. :/

Sorry I couldn't be of more help, good luck!
/Christoffer

**Comment by gilhornung** [comment]
Reopening the discussion...

Regarding the required use of two samples - The problem is that we are working with FFPE samples, and there is very high variability just due to the year the samples were taken (probably due to degradation with time and/or different people that prepared the FFPE samples). So I feel that having two "normal" samples from two different preparation years just inserts way too much variability.

I am thinking of bypassing the two-normals requirement by producing two bam files which are downsampled versions of the normal sample. It will be an underestimate of the variation, but is it really that critical? I think it might be better then using two distant FFPE batches.

**Comment by ChristofferFlensburg** [comment]
Hey!

Yeah, in principle that works. The low variance will only affect the coverage part of the CNA analysis, and underestimated variance is corrected for (this part usually works surprisingly well...), so shouldn't be too big a deal if the algorithms do their thing properly. You can track this in voomVariance and varianceBoost in the diagnostics subdirectory of the plots. This should work fine if your matched normal is clean.

Just be aware that if your somatic mutations are present in the reference normals (due to cancer contamination in the normal), they will be filtered out from the analysis, and won't be called as somatic. I seemed like that potentially was the case for you, so perhaps better to run with any other unrelated normal sample(s), even if that introduces variance. Or maybe try running both and see what you get.

You can look for filtered SNVs present to lower degree in the normal in the scatter plot, in the "allFlagged.png" between a cancer and the normal. You will see filtered somatics as grey or orange circles present at like ~10% VAF in the normal, and closer to 50% in the cancer (depending on clonality and local CNA). They will be filled blue or red circles if not filtered.
