### ISSUE TITLE
CNAsegments table columns description ?

### ISSUE THREAD

**Issue by HugoMananet** [ChristofferFlensburg/superFreq#71]
Hello,

I am a relatively new user of superFreq (thanks for this tool btw), and i'm principally interested in using its CNA analysis part. I already started to use superFreq on some data to compare superFreq results with known CNV in the data and mainly found what was expected.

The output that i use is the CNAsegments table in the 'data' folder as well as the png generated in the 'CNV' folder. 

Is it ok to use this table as result for the CNA calling ?

I searched but didn't find a description of the columns of the output CNAsegments table (like it is provided for the Somatic variants table in the manual). I found only that the 'M' columns indicated the log2FC (and so CN=2*2^M), and that 'width' was "used as basis for donstream uncertainty estimates"

Could you tell me if there is such a description provided for this table in the tool docs or publication, if not could you provide a brief description of the columns of the output table CNAsegments ?

Thanks,
Hugo

**Comment by ChristofferFlensburg** [comment]
Hi Hugo,

Yes that file represents the final calls and there are a lot of columns in there that are not documented well or at all. Many of them are internal stats that no one really needs to care about I think. I'll explain the columns you need to care about.

You are correct that M is the log2 LFC against the reference normals with respect to two copies (that goes for X and Y as well, the reference normal read counts are corrected depending on sex). Note that these LFCs also depend on the ploidy call, so that if superFreq thinks that there's been a geneome duplication, most M will be closer to 1 than to 0. Width is indeed the error estimate of M.

otherwise the important columns are
f - BAF
ferr - BAF error estimate
call - the copy number call (so AB is normal, AAB is gain, AAA is gain and LOH, CL is "complete loss" so zero copies)
clonality - the fraction of cells in the sample (so not purity corrected) with the CNA
clonalityError - the error estimate of the clonality

and I think you can guess the chr, start, end, genes columns.
x1 and x2 - start and end in genome-wide coordinate, a single position coordinate superFreq uses that runs across all chr1 (x=1) to chrY (x around 3e9).
There is also a column that lists COSMIC census genes in the segment, which can be useful when you have a CNA and want to guess what genes may help select the event.

Is that what you need? Let me know if you need anything else.

Where is a good place to add this in the documentation do you think? :/

**Comment by HugoMananet** [comment]
Hi Christoffer,

It was exactly what i needed. 

I think the ideal place to add that is in the manual in 5.1.6 : 'Coverage LFC by gene/exon' since it already explains some of the output of this table.

Thanks for the fast and clear answer ! 
Hugo

**Comment by HugoMananet** [comment]
I also had a question related to issue #9, should i ask it here, create another issue or reopen the issue in question ?

Thanks again,
Hugo

**Comment by ChristofferFlensburg** [comment]
Hmm, not sure what is proper github etiquette. Probably reopen that thread if you think it's the same issue, as in people with that issue will be interested in the solution to your problem? Otherwise a new issue? I probably wouldn't use the same issue for two unrelated problems. 🤷‍♂️
