### ISSUE TITLE
Error in quantile.default

### ISSUE THREAD

**Issue by gsiegwald** [ChristofferFlensburg/superFreq#72]
Dear Christoffer,

Thank you for this very useful tool.

I am new to use superfreq, and I am testing it with 3 exome samples from the same patient.

Everything seems to work fine until the variance boost step, where I get the following error :

```
No boost needed for biological variance.
Error in quantile.default(abs((CR$M[-1] - CR$M[-last])/sqrt((CR$width[-1])^2 +  :
  missing values and NaN's not allowed if 'na.rm' is FALSE
```

Unfortunately I haven't been able to understand where it could come from, do you have an idea?

(I am using R 4.0.3, I can send you the log file if needed)

Thank you,

Guillaume

**Comment by ChristofferFlensburg** [comment]
Hi Guillaume,

I can't tell from that error what went wrong. Please do send the logfile located in Rdirectory/patientName/runtimeTracking.log (it shows your metadata, but no identifying variants), maybe there are some clues in there.

I've only tested superFreq it up to R 4.0.0, so let's keep that as a possible reason as well.

thanks
/Christoffer

**Comment by gsiegwald** [comment]
Hi Christoffer,

Thank you for your quick response ! 

I will switch to R 4.0.0 to be cautious.

I think I've understood why I got the error (I was using a subset of the data on one chromosome), however I've launch a new run with 3 samples I have a new error for which I don't find a solution :

```
WARNING: variants does not have same number of rows in all elements in matchTodbSNPs. This is not intended and is due to an upstream error. Likely to crash with unrelated hard-to-interpret error.

Importing dbSNP allele frequencies from superFreqResources/dbSNP/hg38/dbAFnew.Rdata...done. Match against variants...Error in `$<-.data.frame`(`*tmp*`, "db", value = c(TRUE, TRUE, TRUE, TRUE,  :
  replacement has 167278 rows, data has 166109
Calls: superFreq ... matchTodbSNPs -> lapply -> lapply -> FUN -> $<- -> $<-.data.frame
In addition: Warning messages:
1: In mclapply(1:Nbatch, function(batchI) { :
  1 function calls resulted in an error
2: In FUN(X[[i]], ...) :
  shareVariants found 1169 positions where only some samples have data, such as x=2672409383267240943526724216332672421945267242409626724242172672424444267247074326724707432672471129. This is likely to cause a crash. Cause is likely upstream related to reading out the variant information from the BAMs.
3: In matchTodbSNPs(variantsBI, dir = dbDir, genome = genome, cpus = cpus) :
  variants does not have same number of rows in all elements in matchTodbSNPs. This is not intended and is due to an upstream error. Likely to crash with unrelated hard-to-interpret error.
Execution halted

```
I've joined the runtimeTracking.log file :
[runtimeTracking.log](https://github.com/ChristofferFlensburg/superFreq/files/5995428/runtimeTracking.log)

Do you know where it could come from ?

Thank you for your help,

Guillaume

**Comment by ChristofferFlensburg** [comment]
Let's go by the warning message saying that the problem was related to reading from the BAM at some point. It seems to fit with the first warning that there was an error in one of the parallelised batches of variants. Unfortunately R doesn't output error messages within parallelised threads, so we only get the warning that there was an error. :/

First, to exclude memory related issues (R doesn't handle memory well when parallelising), maybe decrease to maybe 5-10 cpus and run again. delete positions.Rdata (or similar) and variants.sample_41.Rdata from the R output directory first though, or it'll read in the variants with the errors.

If that gives the same error/warnings, I think the easiest way is to run on single thread (cpus=1, again delete the variants Rdata), so that we actually get to see the error that produced the warning in 1. It'll need to run a few hours or at worst overnight, but is likely to make it much easier to troubleshoot.

**Comment by gsiegwald** [comment]
It was indeed a parallelization problem, I reduced the configuration to 10 cpus/ 150Go Ram and it seems to work well :) 
Thanks a lot for your help
