### ISSUE TITLE
Extracting tumour ploidy value from Rdata ?

### ISSUE THREAD

**Issue by HugoMananet** [ChristofferFlensburg/superFreq#75]
Hi Christoffer,

I was wondering if it was possible to extract ploidy values from superfreq results other than the graph given in the diagnostics/ploidy/ repertory from the results.

I found an answer in issue #9 and implemented the code you gave. 

```
extractPloidy = function(truthData) {
  xs = chrToX(truthData$fCsExon$annotation$Chr, truthData$fCsExon$annotation$Start)
  weight = truthData$fCsExon$counts[,'normal1']
  weightInRegion = function(x1, x2) sum(weight[xs > x1 & xs < x2])
  weightsInRegion = function(xs1, xs2) sapply(1:length(xs1), function(i) weightInRegion(xs1[i], xs2[i]))
  
  cnvCancer = truthData$clusters$cancer$clusters
  cancerPloidy = 2*sum(weightsInRegion(cnvCancer$x1,cnvCancer$x2)*2^cnvCancer$M)/sum(weight)
  cnvNormal1 = truthData$clusters$normal1$clusters
  normal1Ploidy = 2*sum(weightsInRegion(cnvNormal1$x1,cnvNormal1$x2)*2^cnvNormal1$M)/sum(weight)
  cnvNormal2 = truthData$clusters$normal2$clusters
  normal2Ploidy = 2*sum(weightsInRegion(cnvNormal2$x1,cnvNormal2$x2)*2^cnvNormal2$M)/sum(weight)
  return(list('normal1'=normal1Ploidy, 'normal2'=normal2Ploidy, 'cancer'=cancerPloidy))
}
```

With this method, I find a ploidy value which is close but different from the one given in the diagnostics/ploidy/ graphs from the results.

For example, i have this sample for which i get 1.91 as ploidy value from the plots, 
![N17 323 T](https://user-images.githubusercontent.com/16399564/109523069-39a65680-7aaf-11eb-8fff-0992df169c03.png)

 but when i try to extract it with the code, i get 2.00643824642096 as cancerPloidy value (the ploidy from the tumor is what i want in the end).

What am i missing here ?

Thanks
Hugo

**Comment by ChristofferFlensburg** [comment]
Hi!

Hmm, looking at that piece of code from the 2017 issue, it's actually not the standard way of calculating ploidy. That code was with the purpose of renormalising library size based on ploidy, so it is weighted by read counts in the genes, which shouldn't be relevant for a standard ploidy calculation. So that reply is a bit misleading, not sure what 2017 me was thinking, sorry.

Luckily it's easier to calculate ploidy the standard way. You just average the total copy number (`2*2^cna$M`) across the segments, weighted by segment size (`cna$x2-cna$x1`). So typing by hand without testing (I'm sure you can fix it if I write bugs)
```
sum(2*2^cna$M*(cna$x2-cna$x1))/sum(cna$x2-cna$x1)
```
I think that should reproduce the number in the plot...

You can exclude sex chromosomes (superFreq returns absolute, not relative, copy numbers for sex chromosomes, so a male sample with no CNAs will have one copy of X and Y called, giving a bit lower ploidythan a normal female sample) if you want with `nonSexSegments = !(superFreq::xToChr(cna$x1, genome='hg19') %in% c('X', 'Y'))` where you insert whatever genome you're using, and you then subset in the weighted sum.

Note that superFreq does not explicitly call a purity, and this is the mean ploidy across all cells in the sample. So if the cancer has a ploidy of 4, but the sample is 50% normal cells, this will give you a ploidy of 3. So keep that in mind when comparing to other methods that return cancer-ploidy and purity, where you have to scale back their ploidy towards 2 using the purity to reproduce the superFreq number.

Is that what you need?
cheers,
/Christoffer

**Comment by HugoMananet** [comment]
Hi Christopher, 

Sorry for the late answer...

Yes it is exactly what i needed !

Thanks again !
Hugo
