### ISSUE TITLE
Error in base::basename(path, ...) : a character vector argument expected

### ISSUE THREAD

**Issue by deb0612** [ChristofferFlensburg/superFreq#85]
Dear sir:
I tried
data =superFreq(file, normalDirectory=normalDirectory,
              Rdirectory=Rdirectory, plotDirectory=plotDirectory, reference=reference, genome=genome,
              cpus=cpus, mode=mode)
But I got error below:
[runtimeTracking.log](https://github.com/ChristofferFlensburg/superFreq/files/6640274/runtimeTracking.log)

Normal directory: /NGS_Storage/Debbie/RNA-seq/variant_calling_20210602/RSEM/referenceNormals
Normal coverage directory: /NGS_Storage/Debbie/RNA-seq/variant_calling_20210602/RSEM/referenceNormals
dbSNP directory: superFreqResources/dbSNP
capture regions: will be downloaded from superFreq server.
Plotting to /NGS_Storage/Debbie/RNA-seq/variant_calling_20210602/RSEM/plots/RNA-leukemia002A
Saving R files to /NGS_Storage/Debbie/RNA-seq/variant_calling_20210602/RSEM/R/RNA-leukemia002A
Genome is hg38
Running in  RNA  mode.
exacPopulation is all
Running on at most 4 cpus.
Rare germline variants are shown in output.

Parameters for this run are:
   maxCov:              150
   systematicVariance:  0.03
   cloneDistanceCut:  2.326348
   cosmicSalvageRate:  0.001

Error in base::basename(path, ...) : a character vector argument expected

**Comment by ChristofferFlensburg** [comment]
Hey!

That part is where the reference normal BAM files are identified. I think it doesn't find any BAM files. I really thought it'd make a more informative error message if it didn't find any bams, so seems I need to look into and probably fix that.

SuperFreq expects the reference normal BAM files (and .bai index files) to be (linked) in the a subdirectory called `bam` in the reference normal directory. It also looks in top level of reference normal directory just in case. So that'd be `NGS_Storage/Debbie/RNA-seq/variant_calling_20210602/RSEM/referenceNormals/bam` and `NGS_Storage/Debbie/RNA-seq/variant_calling_20210602/RSEM/referenceNormals` in your case. I think SuperFreq didnt find any BAM files there, which caused the crash.

Let me know if that solves it.
