### ISSUE TITLE
wget download is not working

### ISSUE THREAD

**Issue by arpanda** [ChristofferFlensburg/superFreq#89]
While running the script, I am getting the below error.

```
--2022-03-22 14:11:48--  http://gitlab.wehi.edu.au/flensburg.c/superFreq/raw/master/captureRegions/mm10exons.named.dn.bed
Resolving gitlab.wehi.edu.au (gitlab.wehi.edu.au)... 128.250.252.207
Connecting to gitlab.wehi.edu.au (gitlab.wehi.edu.au)|128.250.252.207|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://gitlab.wehi.edu.au/flensburg.c/superFreq/raw/master/captureRegions/mm10exons.named.dn.bed [following]
--2022-03-22 14:11:49--  https://gitlab.wehi.edu.au/flensburg.c/superFreq/raw/master/captureRegions/mm10exons.named.dn.bed
Connecting to gitlab.wehi.edu.au (gitlab.wehi.edu.au)|128.250.252.207|:443... connected.
ERROR: cannot verify gitlab.wehi.edu.au's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=R3’:
  Issued certificate has expired.
To connect to gitlab.wehi.edu.au insecurely, use `--no-check-certificate'.
Error in download.file(url, destfile = destFile, method = "wget") :
  'wget' call had nonzero exit status
Calls: superFreq ... superFreq -> analyse -> downloadCaptureRegions -> download.file
Execution halted
```

I can manually download that file using `--no-check-certificate` parameter. But not sure how to specify the path so that it will not try to download it. Could you please help me to solve it. 

Thanks
Arijit

**Comment by VladimirShitov** [comment]
Hello, @arpanda . I faced the same problem. Luckily for us, script [downloadSuperFreqResources.R](https://github.com/ChristofferFlensburg/superFreq/blob/master/R/downloadSuperFreqResources.R) contains checks of the existence of files:
```r
if ( !file.exists(destFile) ) download.file(url, destfile = destFile, method="wget")
```

So you can manually download the files to the directory, which you use as "Rdirectory", when running superfreq. Just run superfreq, get the link to the file from the error, and download it via wget with `--no-check-certificate`

**Comment by VladimirShitov** [comment]
Update: you should download files with `.bed` format in the another directory, created by superFreq. In my case it is named "14" for some reason

**Comment by VladimirShitov** [comment]
And you will also need to manually download files to the superFreqResources directory, which is created in the same location with your script. Run the script once to create the directory structure and empty files inside dirs. Then download the files manually using links in the [downloadSuperFreqResources.R](https://github.com/ChristofferFlensburg/superFreq/blob/master/R/downloadSuperFreqResources.R) script.

**Comment by ChristofferFlensburg** [comment]
Hey!

Sorry for being slow.

Yeah certificates are tricky. It makes it sound like the error is on the server side, and sometimes it is, but it can also be due to downloader side. Did you get the same issue recently @VladimirShitov ? I might need to check with HPC ppl here.

For manual download:
You can find the urls and file names in downloadSuperFreqResources.R, and they are called in analyse.R, around line 220 to 250, that should show the expected directory structure.

For mm10, it should look like this, where the top level directory path (default `superFreqResources`) is an input to the `superFreq(..., resourceDirectory"myResourceDirectory"')` call.

<img width="340" alt="Screen Shot 2022-03-30 at 11 33 55 am" src="https://user-images.githubusercontent.com/9857320/160728004-d6db0bcb-4bf3-4514-ab6f-c768350501ca.png">

The 3 capture regions .bed files go in `myRdirectory/myIndividual/*.bed`, downloaded by `downloadCaptureRegions(directory="myRdirectory/myIndividual", genome="mm10", mode="exome")` in your case.

Is that enough to get you going? Let me know!
