### ISSUE TITLE
Output of purity and ploidy estimates

### ISSUE THREAD

**Issue by gilhornung** [ChristofferFlensburg/superFreq#9]
Hi Christoffer,

Lot's of correspondence today... Hope I am not bothering you too much.

I can't find where the purity and ploidy estimates for each sample are found in. I couldn't find it in the documentation or the output files.

Gil

**Comment by ChristofferFlensburg** [comment]
Hey!

All good, hopefully it'll improve the software or be useful for others as well.

SuperFreq doesn't explicitly output those, as they are not explicitly calculated as most other CNA callers do. Each copy number segment is allowed its own clonality (or purity if you want), and while the coverage is normalised, it's in terms of a normalisation factor which is related to but not equal to the ploidy. You can see how this works in the maypole plots in plots/diagnostics/CNVcall. For purity of the sample, you can look at recurring (high) clonalities called in the bottom panel of the CNA plots, or you can look at the largest clone in the river plots. For ploidy... you can calculate the average copy number over all regions and cells if you want, but I've never really bothered to output that. Why do you want to know the ploidy? To spot genome duplication? I think that'll be clear enough anyway from the CNA plot.

I actually did the ploidy calculation for some in silico simulations a while ago....

```
extractPloidy = function(truthData) {
  xs = chrToX(truthData$fCsExon$annotation$Chr, truthData$fCsExon$annotation$Start)
  weight = truthData$fCsExon$counts[,'normal1']
  weightInRegion = function(x1, x2) sum(weight[xs > x1 & xs < x2])
  weightsInRegion = function(xs1, xs2) sapply(1:length(xs1), function(i) weightInRegion(xs1[i], xs2[i]))
  
  cnvCancer = truthData$clusters$cancer$clusters
  cancerPloidy = 2*sum(weightsInRegion(cnvCancer$x1,cnvCancer$x2)*2^cnvCancer$M)/sum(weight)
  cnvNormal1 = truthData$clusters$normal1$clusters
  normal1Ploidy = 2*sum(weightsInRegion(cnvNormal1$x1,cnvNormal1$x2)*2^cnvNormal1$M)/sum(weight)
  cnvNormal2 = truthData$clusters$normal2$clusters
  normal2Ploidy = 2*sum(weightsInRegion(cnvNormal2$x1,cnvNormal2$x2)*2^cnvNormal2$M)/sum(weight)
  return(list('normal1'=normal1Ploidy, 'normal2'=normal2Ploidy, 'cancer'=cancerPloidy))
}
```
That assumes that the input "truthData", which is the output from superFreq() or from superFreq::loadData(), has samples named "cancer", "normal1" and "normal2", but you can should be able to change that to fit your purposes.

**Comment by gilhornung** [comment]
Hi,

Ploidy isn't important for me, I just assumed it would be there.

I understand that purity is the highest estimated clonality. Is there a way to extract the estimated purity from clusters.RData, e,g:
`purity = max( clusters$WS9.T$clusters$clonality[ ... Some filtering conditions .... ]  )`

What would be the appropriate filtering conditions?

Thanks,

Gil

**Comment by ChristofferFlensburg** [comment]
If you only have a few samples, the best way is to look at the plot, and see where most of the top clonalities cluster. The last plot in the readme onthis github page is a good example of that, where you see that there are like 5 CNAs all clustering just above 70% clonality. There is a very crude clustering built in which is shown as bands (representing confidence interval) in the clonality panel that can guide you. That clustered clonality (and error) is also in the clusters$sample data frame, in one of the later columns. Beware though, as the Y chromosome is often called at like 98% purity complete loss (CL), so may want to exclude sex chromosomes. The highest cluster exluding sex chromsomes should be a decent estimate of purity, although not infallible of course.

Otherwise just use the main cancer clone from the clonal tracking, and you get the power from the SNVs as well.
